### ISSUE TITLE
Change hover time

### ISSUE THREAD

**Issue by schroef** [bazitur/brackets-python-tools#1]
Really like this addon, but have 2 questions. How can i set the timer for the hover effect faster, it to slow for poping up. Im talking about the warning icons in the main window. 

Also i saw on main page there is inline documentation. How or where can i view this?

**Comment by TechJA** [comment]
Hi bazitur,
congrats for your extension for brackets

I have the same question has @schroef :
Ho can I view inline documentation?
Autocompletion and linting works fine

I already installed python 3.6.3, flake8 and docutils

**Comment by bazitur** [comment]
Hello,
I've fixed the bug. Try updating the extension and pressing `Ctrl + K`.

**Comment by schroef** [comment]
ctrl + K on OSX deletes a line
cmd + D shows hover error "No quick docs available"

<img width="460" alt="screen shot 2017-12-16 at 16 34 56" src="https://user-images.githubusercontent.com/6923008/34074134-2d28384a-e27f-11e7-92e8-353159cace94.png">

**Comment by bazitur** [comment]
Hi @schroef,
It is done so that Quick Docs are available only when function or class is under the cursor. See: 
![default](https://user-images.githubusercontent.com/26185574/34074176-b534f102-e2ba-11e7-806e-77ba60a7e724.png)

**Comment by schroef** [comment]
Ps i think you adjusted the quickdos window, thats the window with the hints right?
It does seem to work when i go to location type, go to other location and return and press cmd + K

What i meant by hover time was for the error and warnings in the gutter
<img width="416" alt="screen shot 2017-12-16 at 16 40 52" src="https://user-images.githubusercontent.com/6923008/34074183-1f69ff58-e280-11e7-933d-d96c71a66e3a.png">

**Comment by schroef** [comment]
its the one which shows error.html cant seem to find something about time

**Comment by schroef** [comment]
PS i read something about you wanting to speedup the parsing. Isnt it possible to get the window height of the brackets. I think if you now the height you now howmany lines are visible. When you calculate the difference you can let the parser only do that section.

idea???

**Comment by schroef** [comment]
@bazitur  Where is that setting? i dont see time.sleep in your code. The hover time is much slower and takes 2/3 longer than say the over function show image in html page address

Overlooked that message :)

**Comment by TechJA** [comment]
new version installed, was needed to remove your extension manually because Brackets gave error for update your extension, and now the inline documentation works fine. It will be nice if you can add a setting for users can change the font size because is the used bigger

The delay of autocompletion window, for me, is too long. Could it's possible to add  a setting for users can change the delay time too?

Thanks!

**Comment by bazitur** [comment]
@TechJA,
The problem is that autocompletion is done via python script running in another process. Brackets API provides connection to it through Node, and there's probably no way for route Brackets → pipe → Node → pipe → Python → pipe → Node → pipe → Brackets to be faster. The bottleneck is asynchronous pipe between Node and Brackets.

**Comment by TechJA** [comment]
Thanks for the reply
understood, no problem ;)

**Comment by schroef** [comment]
So hover time cant be changed, where is it controlled? Something most control the time right?

**Comment by bazitur** [comment]
@schroef,
It simply cannot be faster because of Brackets' delay while communicating with Node.

**Comment by schroef** [comment]
oh thats a pitty then, to bad.
